In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
random_array = np.random.randint(0, 10, (3, 5))
random_array

array([[2, 5, 3, 7, 1],
       [2, 3, 2, 5, 5],
       [7, 1, 9, 9, 5]])

In [5]:
random_array2 = np.arange(0, 10, 3)
random_array2

array([0, 3, 6, 9])

In [8]:
random_array3 = np.random.random([5,3])
random_array3

array([[0.09749334, 0.59571618, 0.24821993],
       [0.18403805, 0.8507359 , 0.42709142],
       [0.01787458, 0.59509514, 0.80653332],
       [0.2957163 , 0.2407379 , 0.81884316],
       [0.03515408, 0.36866117, 0.58223713]])

## 3 Viewing Arrays and Matrices

In [ ]:
np.unique